#!/usr/bin/env bash

##
# Nginx control script
# by: Uros Zekar, 2009/04/17

# change to your nginx path
NGINX_PATH=/opt/nginx

if [ "$(id -u)" != "0" ]; then
	echo "This script must be run as root."
  set $1=
fi

case $1 in
start)
  echo "starting nginx"
  $NGINX_PATH/sbin/nginx
  ;;

stop)
  echo "stopping nginx"
  if [ -f $NGINX_PATH/logs/nginx.pid ]; then
    kill `cat $NGINX_PATH/logs/nginx.pid`
  fi
  ;;

restart)
  echo "restarting nginx"
  if [ -f $NGINX_PATH/logs/nginx.pid ]; then
    kill `cat $NGINX_PATH/logs/nginx.pid`
  fi
  $NGINX_PATH/sbin/nginx
  ;;

test)       
  echo "testing nginx config"
  $NGINX_PATH/sbin/nginx -t -c $NGINX_PATH/conf/nginx.conf
  ;;

*)
  printf "Usage: sudo %s: [start | stop | restart | test]\n" $(basename $0) >&2
  exit 2
  ;;
esac