#!/usr/bin/env bash

##
# Nginx control script
# by: Uros Zekar, 2009/04/17

# change to your nginx path
NGINX_PATH=/opt/nginx

# optional: change the pid & conf location
NGINX_PID=$NGINX_PATH/logs/nginx.pid
NGINX_CONF=$NGINX_PATH/conf/nginx.conf

if [ "$(id -u)" != "0" ]; then
	echo "This script must be run as root."
  set $1=
fi

case $1 in
start)
  echo "starting nginx"
  $NGINX_PATH/sbin/nginx
  ;;

stop)
  echo "stopping nginx"
  if [ -f $NGINX_PID ]; then
    kill `cat $NGINX_PID`
  fi
  ;;

restart)
  echo "restarting nginx"
  if [ -f $NGINX_PID ]; then
    kill `cat $NGINX_PID`
  fi
  $NGINX_PATH/sbin/nginx
  ;;

reload)
  echo "reloading nginx config"
  if [ -f $NGINX_PID ]; then
    kill -HUP `cat $NGINX_PID`
  fi
  ;;

test)       
  echo "testing nginx config"
  $NGINX_PATH/sbin/nginx -t -c $NGINX_CONF
  ;;

*)
  printf "Usage: sudo %s: [start | stop | restart | reload | test]\n" $(basename $0) >&2
  exit 2
  ;;
esac